<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Xsearch
 */
?>
<?php
/**
 * @var \Amasty\Xsearch\Block\RelatedSearchTerms $block
 */
?>
<?php
/** @var \Magento\Search\Model\Query[] $data */
$data = $block->getItems();
if (count($data)):?>
    <dl class="block">
        <dt class="title"><?= /* @escapeNotVerified */ __($block->getTitle()) ?></dt>
        <?php foreach ($data as $additionalInfo) : ?>
            <dd class="item">
                <a href="<?= /* @escapeNotVerified */ $block->getLink($additionalInfo->getQueryText()) ?>">
                    <?= $block->escapeHtml($additionalInfo->getQueryText()) ?>
                </a>
                <?php if ($block->isShowResultsCount()): ?>
                    <span class="count">(<?= /* @escapeNotVerified */ $additionalInfo->getNumResults() ?>)</span>
                <?php endif; ?>
            </dd>
        <?php endforeach; ?>
    </dl>
<?php endif; ?>
