<?php
	$product = $block->getProduct();
	$sku = $product->getSku();
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$fileSystem = $objectManager->create('\Magento\Framework\Filesystem');
	$mediaPath = $fileSystem->getDirectoryRead(\Magento\Framework\App\Filesystem\DirectoryList::MEDIA)->getAbsolutePath();
	$datasheetPath = $mediaPath . 'guides/' . $sku . '.pdf';
	$userguidePath = $mediaPath . 'guides/' . $sku . '-userguide.pdf';
	$qsguidePath = $mediaPath . 'guides/' . $sku . '-qsguide.pdf';
	$datasheetUrl = '/pub/media/guides/'.$sku.'.pdf';
	$userguideUrl = '/pub/media/guides/'.$sku.'-userguide.pdf';
	$qsguideUrl = '/pub/media/guides/'.$sku.'-qsguide.pdf';
?>
<h2>Support & Downloads</h2>
<div class="content">
	<h4 style="margin-top: 20px;">Technical Details</h4>
	<?php if (file_exists($datasheetPath)) : ?>
		<ul style="padding-left: 20px;">
			<li>
				<a href="<?php echo $datasheetUrl; ?>">Data Sheet</a>
			</li>
			<?php if (file_exists($userguidePath)) : ?>
				<li>
					<a href="<?php echo $userguideUrl; ?>">Userguide</a>
				</li>
			<?php endif; ?>
			<?php if (file_exists($qsguidePath)) : ?>
				<li>
					<a href="<?php echo $qsguideUrl; ?>">Quickguide</a>
				</li>
			<?php endif; ?>
		</ul>
	<?php else: ?>
		<p>There are no available datasheets to download.</p>
	<?php endif; ?>
	
</div>