<!-- 
/**
 * @category   Webkul
 * @package    Webkul_MultiEbayStoreMageConnect
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */  -->
<?php
	$loaderPath = $block->getViewFileUrl("Webkul_MultiEbayStoreMageConnect::images/loader.gif");
	$loaderElement = '<img src="'.$loaderPath.'" class=loader style=margin-left:5px></img>'; 

	$releventData = [
		"loaderPath"				=>$loaderPath,
		"formSelector"		=> '#edit_form',
		"saveMapSelector"	=>'.wk-save-mapping',
		'mageCategorySelector'		=> '.mage_category',
		'saveMappingAjaxUrl'		=> $block->getUrl('*/*/savemapping'),
		'getMageChildCategoryAjaxUrl'	=> $block->getUrl('*/*/getmagechildcategory'),
		'ebayCategorySelector'	=> '.ebay_category',
		'getEbayChildCategoryAjaxUrl' 	=> $block->getUrl('*/*/getebaychildcategory')
	];

	$serializedData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($releventData);

?>
<script type="text/x-magento-init">
    {
        "*":{
            "Webkul_MultiEbayStoreMageConnect/js/category-map-plugin":<?php echo $serializedData ?>
        }
    }
</script>