<!-- 
/**
 * @category   Webkul
 * @package    Webkul_MultiEbayStoreMageConnect
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */  -->
<?php
    $_helper = $this->helper('Webkul\MultiEbayStoreMageConnect\Helper\Data');
    $mageTopLevelCate = $_helper->getTopLevelMageCategory();
    $ebayTopLevelCate = $_helper->getTopLevelEbayCategory();
?>
<fieldset class="fieldset wk-mapping-fieldset" id="catmap_base_fieldset"> 
    <legend class="admin__legend legend">
        <span>Map New Category</span>
    </legend><br>
    <button id="wk-save-mapping" title="Save Ebay mapping" type="button" class="button wk-save-mapping primary">
        <span class="button">
            <span><?php echo __('Save Mapping') ?></span>
        </span>
    </button>
    <div>
        <label>
            <span><?php echo __('Store Category') ?></span>
        </label>
        <div class="admin__field-control control">
            <select class="required-entry mage_category required-entry _required select admin__control-select" name="mage_category">
            <?php
            foreach ($mageTopLevelCate as $key => $info) { ?>
                <option value=<?php echo $info['value']; ?>><?php echo $info['label']; ?></option>
           <?php 
            }
            ?>
            </select>
        </div>
    </div>

    <div>
        <label>
            <span>eBay Category</span>
        </label>
        <div class="admin__field-control control">
            <select class="required-entry ebay_category required-entry _required select admin__control-select" name="ebay_category">
            <?php
                foreach ($ebayTopLevelCate as $key => $info) { ?>
                    <option value=<?php echo $info['value']; ?>><?php echo $info['label']; ?></option>
               <?php 
                }
                ?>
            </select>
        </div>
    </div>
</fieldset>