<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Cart
 */
?>
<div id="am-qty" class="amcart-qty-wrap" data-amcart="qty-wrap">
    <label for="am-input" class="amcart-label"><?= $this->escapeHtml(__('Qty'));?></label>
    <span class="amcart-control -minus" data-amcart="qty-minus"></span>
    <span class="amcart-control -plus" data-amcart="qty-plus"></span>
    <span class="amcart-refresh" title="<?= $this->escapeHtml(__('Update'));?>" data-amcart="qty-refresh"></span>
    <input class="amcart-input" id="am-input" maxlength="12" title="Qty" size="7" type="number"
           value="<?= $this->getQty(); ?>"
           name="item_qty"
           data-amcart="qty-input">
    <input type="hidden" name="form_key" id="form-key"
           value="<?= $this->getFormKey(); ?>"
           data-amcart="qty-form-key"/>
    <input type="hidden" name="item_id" id="quote_id"
           value="<?= $this->getQuoteId(); ?>"
           data-amcart="qty-quote-id"/>
</div>
