<!-- 
/**
 * @category   Webkul
 * @package    Webkul_MultiEbayStoreMageConnect
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */  -->
<script type='text/javascript'>
	console.log(' window close iwnsdf ');
	window.opener.location.reload(true);
	window.close();
</script>
