<!-- 
/**
 * @category   Webkul
 * @package    Webkul_MultiEbayStoreMageConnect
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */  -->
<div class="page-main-actions">
	<div class='wk-product-import-buttons'>
		<button id="wk-import-order" title="Save Ebay mapping" type="button" class="button wk-import-order primary">
	        <span class="button">
	            <span><?php echo __('Import Order From eBay'); ?></span>
	        </span>
	    </button>
	    <button id="wk-run-order-profiler" title="Save Ebay mapping" type="button" class="button wk-run-order-profiler primary">
	        <span class="button">
	            <span><?php echo __('Run Profiler'); ?></span>
	        </span>
	    </button>
	</div>
</div>