<!-- 
/**
 * @category   Webkul
 * @package    Webkul_MultiEbayStoreMageConnect
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */  -->
<?php
	$id = $block->getRequest()->getParam('id');
	$releventData = [
		'importOrderSelector' => '#wk-import-order',
		'importAjaxUrl'	=> $block->getUrl('*/ebayorder/import'),
		'profilerSelector'	=> '#wk-run-order-profiler',
		'profilerAjaxUrl'	=> $this->getUrl('*/ebayorder/profiler',['id'=>$id])
	];

	$serializedData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($releventData);

?>
<script type="text/x-magento-init">
    {
        "*":{
            "Webkul_MultiEbayStoreMageConnect/js/order-map-plugin":<?php echo $serializedData ?>
        }
    }
</script>