<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Cart
 */
?>
<?php
// @codingStandardsIgnoreFile
/* @var $block \Amasty\Cart\Block\Product\Related | \Amasty\Cart\Block\Product\Crosssell */
?>

<?php
switch ($type = $block->getBlockType()) {
    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $items = $block->getItems();
            $limit = 3;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;
    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $items = $block->getItems();
            $limit = 3;
            $showAddTo = true;
            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;
    default:
        $exist = false;
        break;
}
?>

<?php if ($exist):?>
    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?= /* @escapeNotVerified */ $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= /* @escapeNotVerified */ $limit; ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle; ?>">
        <?php else: ?>
            <div class="block <?= /* @escapeNotVerified */ $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?= /* @escapeNotVerified */ $limit; ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle; ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block related">
    <?php endif; ?>
    <div class="am-related-title">
        <span class="am-title"><?= /* @escapeNotVerified */ $this->getHelper()->getBlockTitle(); ?></span>
    </div>
    <span class="am-subtitle"><?= /* @escapeNotVerified */ $this->getHelper()->getBlockSubTitle(); ?></span>
    <div class="block-content content" aria-labelledby="block-<?= /* @escapeNotVerified */ $class?>-heading">
        <div class="products wrapper grid products-grid products-<?= /* @escapeNotVerified */ $type; ?> am-slider owl-carousel">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                <?php $available = ''; ?>
                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($type == 'related' || $type == 'upsell'): ?>
                        <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<div class="item product product-item">' : '</div><div class="item product product-item">' ?>
                <?php else: ?>
                        <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<div class="item product product-item">' : '</div><div class="item product product-item">' ?>
                <?php endif; ?>
                <div class="product-item-info <?= /* @escapeNotVerified */ $available; ?>">
                    <div class="am-product-image product actions product-item-actions">
                        <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                            <?= $block->getImage($_item, $image)->toHtml(); ?>
                        </a>
                        <?php if ($showWishlist || $showCompare): ?>
                            <div class="secondary-addto-links actions-secondary am-actions-wrapper" data-role="add-to-links">
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                    <a href="#" <?= $block->getHelper()->getDataPost('wishlist') ?>='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($_item); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?= /* @escapeNotVerified */ __('Add to Wish List') ?>">
                                        <span><?= /* @escapeNotVerified */ __('Add to Wish List') ?></span>
                                    </a>
                                <?php endif; ?>
                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                    <?php
                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                    ?>
                                    <a href="#" class="action tocompare"
                                       <?= $block->getHelper()->getDataPost('compare') ?>='<?= /* @escapeNotVerified */ $compareHelper->getPostDataParams($_item);?>'
                                       data-role="add-to-links"
                                       title="<?= /* @escapeNotVerified */ __('Add to Compare'); ?>">
                                        <span><?= /* @escapeNotVerified */ __('Add to Compare') ?></span>
                                    </a>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">
                                <?= $block->escapeHtml($_item->getName()) ?></a>
                        </strong>

                        <?= /* @escapeNotVerified */ $block->getProductPrice($_item); ?>

                            <?php if ($templateType): ?>
                                <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>

                            <?php if ($showWishlist || $showCompare || $showCart): ?>
                                <div class="product actions product-item-actions">
                                    <?php if ($showWishlist || $showCompare): ?>
                                        <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                <a href="#" <?= $block->getHelper()->getDataPost('wishlist') ?>='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($_item); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?= /* @escapeNotVerified */ __('Add to Wish List') ?>">
                                                    <span><?= /* @escapeNotVerified */ __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                <?php
                                                $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                ?>
                                                <a href="#" class="action tocompare"
                                                <?= $block->getHelper()->getDataPost('compare') ?>='<?= /* @escapeNotVerified */ $compareHelper->getPostDataParams($_item);?>'
                                                   data-role="add-to-links"
                                                   title="<?= /* @escapeNotVerified */ __('Add to Compare'); ?>">
                                                    <span><?= /* @escapeNotVerified */ __('Add to Compare') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                    <?php if ($showCart): ?>
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <button class="action tocart primary"
                                                            data-post='<?= /* @escapeNotVerified */ $postData; ?>'
                                                            type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                    </button>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?= ($iterator == count($items)+1) ? '</div>' : '' ?>
                <?php endforeach ?>
        </div>
    </div>
</div>
<?php endif;?>
<script>
    require([
        'jquery',
        'Amasty_Cart/js/owl.carousel.min',
        'domReady!'
    ], function ($) {
        $(document).ready(function(){
            var itemsPerView = $(window).width() <= 768 ? 1 : 2;
            $(".products-grid.am-slider").owlCarousel({
                items: itemsPerView,
                nav: true,
                navText : ['<p class="am-slider arrow -left"></p>','<p class="am-slider arrow -right"></p>']
            });
        });
    });
</script>
