<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php
$item = $block->getItem();
?>
<tr id="order-item-row-<?= /* @escapeNotVerified */ $item->getId() ?>">
    <td class="col name" data-th="<?= $block->escapeHtml(__('Product Name')) ?>">
        <strong class="product name product-item-name"><?= $block->escapeHtml($item->getName()) ?></strong>
        <?php if ($options = $block->getOptionList()):?>
            <dl class="item-options">
                <?php foreach ($options as $option) : ?>
                    <?php $_formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                    <dt><?= $block->escapeHtml($option['label']) ?></dt>
                    <dd>
                        <?php if (isset($_formatedOptionValue['full_view'])): ?>
                            <?= /* @escapeNotVerified */ $_formatedOptionValue['full_view'] ?>
                        <?php else: ?>
                            <?= /* @escapeNotVerified */ $_formatedOptionValue['value'] ?>
                        <?php endif; ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif;?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) :?>
            <?= $addtInfoBlock->setItem($item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?= $block->escapeHtml(__('SKU')) ?>"><?= /* @escapeNotVerified */ $block->escapeHtml($item->getSku()) ?></td>
    <td class="col price qty" data-th="<?= $block->escapeHtml(__('Price')) ?>">
        <?= $block->getUnitPriceHtml($item) ?>
    </td>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <span><?= $block->getQty() ?></span>
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <span><?= $block->getRowTotalHtml($item) ?></span>
    </td>
</tr>
