<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_ShippingBar
 */
?>
<?php /** @var \Amasty\ShippingBar\Block\Frontend\Bar $block */ ?>
<div data-bind="scope: 'amasty-shipbar-<?= $block->getPosition() ?>'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
            }
        }
    </script>
</div>
